baseURL = 'https://capulongfarms.com/'
languageCode = 'en-ph'
title = 'Farm-to-Table Pampanga | Fresh Produce & Livestock â€“ Capulong Farms'
theme = 'capulong'

[params]
  description = "Fresh produce and farm supplies from Capulong Farms, Philippines"
  whatsapp_number = "966542761620"  # Replace with your actual WhatsApp Business number
  gcash_qr_image = "/images/gcash-qr.png"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Buy & Pay!"
    url = "/#order"
    weight = 2
    [menu.main.params]
      class = "cta-button"
   # Note: the above Call to Action, CTA-button is commented out, to make way for other style
  [[menu.main]]
    name = "Products"
    url = "/#products"
    weight = 3
