baseURL = 'https://capulongfarms.com/'
languageCode = 'en-ph'
title = 'Farm-to-Table Pampanga | Fresh Produce & Livestock â€“ Capulong Farms'
theme = 'capulong'

[params]
  description = "Capulong Farms is a family-owned farm in Lanang, Candaba, Pampanga offering fresh farm produce, livestock, and hands-on agricultural training. Farm-to-table goodness straight from Pampanga."
  whatsapp_number = "966542761620"
  gcash_qr_image = "/images/gcash-qr.png"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Buy & Pay!"
    url = "/#order"
    weight = 2
    [menu.main.params]
      class = "cta-button"
   # Note: the above Call to Action, CTA-button is commented out, to make way for other style
  [[menu.main]]
    name = "Products"
    url = "/#products"
    weight = 3
