name = "Capulong"
license = "MIT"
description = "Custom theme for Capulong Farms"
homepage = "https://capulongfarms.com/"
tags = ["farm", "ecommerce", "simple"]
features = ["responsive"]
min_version = "0.120.0"
